name: Rangsystem
main: Rangsystem\Main
version: 1.0.0
api: 4.0.0
author: L44
description: Ein Rangsystem mit Gruppen, Prefixen & Suffixen

commands:
  setgroup:
    description: Setzt die Gruppe eines Spielers.
    usage: "/setgroup <Spieler> <Gruppe>"
    permission: rangsystem.setgroup

  listgroups:
    description: Listet alle Gruppen auf.
    usage: "/listgroups"
    permission: rangsystem.listgroups

  whois:
    description: Zeigt Informationen über einen Spieler.
    usage: "/whois <Spieler>"
    permission: rangsystem.whois

  setprefix:
    description: Ändert den Prefix einer Gruppe.
    usage: "/setprefix <Gruppe> <Prefix>"
    permission: rangsystem.setprefix

  setsuffix:
    description: Ändert den Suffix einer Gruppe.
    usage: "/setsuffix <Gruppe> <Suffix>"
    permission: rangsystem.setsuffix

permissions:
  rangsystem.setgroup:
    default: op
  rangsystem.listgroups:
    default: true
  rangsystem.whois:
    default: true
  rangsystem.setprefix:
    default: op
  rangsystem.setsuffix:
    default: op
